--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-03-05 20:26:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16398)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id bigint NOT NULL,
    author character varying(250) NOT NULL,
    isbn character varying(255),
    price double precision NOT NULL,
    publication_year integer NOT NULL,
    title character varying(250) NOT NULL,
    categoryid bigint,
    CONSTRAINT book_price_check CHECK ((price >= (0)::double precision)),
    CONSTRAINT book_publication_year_check CHECK (((publication_year <= 2025) AND (publication_year >= 1001)))
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16397)
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16408)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    categoryid bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16407)
-- Name: category_categoryid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN categoryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_categoryid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4909 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user (id, email, password, role, username) FROM stdin;
1		$2a$10$0.CyWO.KVDv.I.LBt/LnMOMMMikflaK3o0z.gjnEaL1nJKwzV1ZUy	USER	user
2		$2a$10$4/4hbxOU1OigHnAAhitiLu7EP43TgdjX.8Nzcyq.UmSsUDSGPFSEK	ADMIN	admin
\.


--
-- TOC entry 4911 (class 0 OID 16398)
-- Dependencies: 220
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book (id, author, isbn, price, publication_year, title, categoryid) FROM stdin;
1	J.R.R. Tolkien	978-951-0-33337-2	19.99	1954	Sormuksen ritarit	1
2	J.R.R. Tolkien	978-951-0-33337-3	19.99	1954	Kaksi tornia	1
3	J.R.R. Tolkien	978-951-0-33337-4	19.99	1955	Kuninkaan paluu	1
\.


--
-- TOC entry 4913 (class 0 OID 16408)
-- Dependencies: 222
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category (categoryid, name) FROM stdin;
1	Fantasy
2	Horror
3	Fiction
\.


--
-- TOC entry 4919 (class 0 OID 0)
-- Dependencies: 217
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_user_id_seq', 2, true);


--
-- TOC entry 4920 (class 0 OID 0)
-- Dependencies: 219
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_seq', 3, true);


--
-- TOC entry 4921 (class 0 OID 0)
-- Dependencies: 221
-- Name: category_categoryid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_categoryid_seq', 3, true);


--
-- TOC entry 4755 (class 2606 OID 16396)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4759 (class 2606 OID 16406)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- TOC entry 4761 (class 2606 OID 16412)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (categoryid);


--
-- TOC entry 4757 (class 2606 OID 16414)
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- TOC entry 4762 (class 2606 OID 16415)
-- Name: book fk2b35frrtu8m7cdfnu300xhnlm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT fk2b35frrtu8m7cdfnu300xhnlm FOREIGN KEY (categoryid) REFERENCES public.category(categoryid);


-- Completed on 2025-03-05 20:26:18

--
-- PostgreSQL database dump complete
--

